### ISSUE TITLE
License

### ISSUE THREAD

**Issue by greenmmq** [dayamuralidharan/California-Urban-Water-Management-Economic-Tool#106]
@dayamuralidharan @KenseyDaly 

This project is currently missing a license. More about licensing software on Github [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) (its a pretty easy process, just copy and paste a `LICENSE.md` file with the appropriate text). 

 It probably should have a license, though what kind is really up to you as the project owner. I'm a fan of the AGPL or GPL v3 [copyleft](https://www.gnu.org/licenses/licenses.html#WhatIsCopyleft) licenses - but ultimately you'll want to evaluate which license best meets your requirements and [choose](https://choosealicense.com/).

**Comment by greenmmq** [comment]
This is a summary of the [implications of not having a license](https://choosealicense.com/no-permission/).

**Comment by KenseyDaly** [comment]
Updated license to AGPL.
